Player gravitation
kpierzynski/Run-Dash pull request #5
Opened 2019-11-08 13:34 UTC by kpierzynski

Dodano prostą możliwość skoku gracza wraz z jego animacją.

2019-11-08 16:34 UTC, michalStarski commented
Imo dodawanie fizyki dla samego gracza nie jest za dobrym pomyslem.
Powinnismy zrobic jakas klase z fizyka z ktorej dziedziczyly by obiekty, ktore beda na ta fizyke podatne.
Wtedy po prostu gracz, czy cokolwiek innego mialyby odziedziczona metode addForce (na wzor z unity), ktora by je ruszala. Przy twoim rozwiazaniu fizyke trzeba by bylo implementowac pojedynczo dla kazdego elementu na mapie.

2019-11-08 17:14 UTC, kpierzynski commented
Rozkminiałem, czy zrobić fizykę jako osobną klasę, ale grawitacja będzie działać tylko gracza i nic więcej. Ale chyba faktycznie masz rację, chociażby czytelność się poprawi.

2019-11-08 17:34 UTC, michalStarski commented
Warto jednak przeniesc to do osobnej klasy, bo w ten sposob bedziemy uodpornieni na jakies ewentualne zmiany w przyszlosci. Moze np. jakas monetka bedzie wyskakiwac do gory przy pojawieniu czy cos. W tym momencie ciezko to stwiedzic wiec zostawmy na to otwarta furtke.

2019-11-11 11:50 UTC, mstarski requested changes

2019-11-11 11:50 UTC, michalStarski commented on GameObject.hpp
> +		int spriteWidth, spriteHeight;
Imo tu trzeba wybrac jedno:
- Albo dajemy pola prywatne i robimy publiczne gettery/settery na pola
- Albo dajemy pola publiczne bez getterów/setterów

W tym momencie tutaj są publiczne pola a do nich gettery/settery co jest trochę zbędne.

2019-11-11 11:50 UTC, michalStarski commented on Physics.cpp
> +Physics::Physics( float x, float y, float width, float height, float density, float friction, b2BodyType bodyType, b2World * world ) {
Tutaj pierdoła ale jak możesz to nie rób takich długich linii bo na mniejszym ekranie (lub podzielonym) ciężej to czytać.
Wstaw tutaj nową linię w którymś miejscu.

2019-11-11 11:50 UTC, michalStarski commented on Player.cpp
> +Player::Player( float x, float y, int spriteWidth, int spriteHeight, int scale, float density, float friction, b2World * world ) : GameObject( x, y, spriteWidth, spriteHeight, scale ), Physics(x,y,sp
Tutaj też wstaw enter plz

2019-11-11 11:50 UTC, michalStarski commented on Player.cpp
>  	if( sf::Keyboard::isKeyPressed(sf::Keyboard::A) ) {
Na dłuższą metę trzeba będzie to sprawdzanie klawiszy porozdzielać do innych plików bo się śmietnik zrobi.

2019-11-11 11:50 UTC, michalStarski commented on Player.cpp
>  		this->isRunning = true;
Te zmiany stanu mozna by było ładnie zamknąć w jakiejś funkcji zamiast manualnie je przypisywać:
```
private void Player::runLeft() {
   this->isRunning = true;
   ....
}
```

2019-11-11 11:50 UTC, michalStarski commented on Player.hpp
> +		Player( float x, float y, int spriteWidth, int spriteHeight, int scale, float density, float friction, b2World * world );
Enter plz

2019-11-11 11:50 UTC, michalStarski commented on main.cpp
>  	TFrame framesIdle[4] = {
To będzie trzeba na dłuższą metę wyrzucić do innego pliku (te definicje ramek)

2019-11-11 11:50 UTC, michalStarski commented on main.cpp
> +		window.draw( player ); //Rysowanie gracza
Player dziedziczy z GameObject, który ma swoją metodę draw afaik. Tutaj można ją wywołać zamiast tego.

2019-11-12 09:36 UTC, closed without merging